// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BODY_PROTOCOL_L2W_H_
#define FLATBUFFERS_GENERATED_BODY_PROTOCOL_L2W_H_

#include "flatbuffers/flatbuffers.h"

#include "id_generated.h"

#endif  // FLATBUFFERS_GENERATED_BODY_PROTOCOL_L2W_H_
