// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BODY_PROTOCOL_C2S_H_
#define FLATBUFFERS_GENERATED_BODY_PROTOCOL_C2S_H_

#include "flatbuffers/flatbuffers.h"

#include "id_generated.h"

namespace Protocol {
namespace C2S {

struct AckLogin;
struct AckLoginBuilder;

struct AckLogin FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AckLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_A = 6
  };
  Protocol::C2S::eID id() const {
    return static_cast<Protocol::C2S::eID>(GetField<uint32_t>(VT_ID, 20001));
  }
  const flatbuffers::Vector<float> *a() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_A);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_A) &&
           verifier.VerifyVector(a()) &&
           verifier.EndTable();
  }
};

struct AckLoginBuilder {
  typedef AckLogin Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(Protocol::C2S::eID id) {
    fbb_.AddElement<uint32_t>(AckLogin::VT_ID, static_cast<uint32_t>(id), 20001);
  }
  void add_a(flatbuffers::Offset<flatbuffers::Vector<float>> a) {
    fbb_.AddOffset(AckLogin::VT_A, a);
  }
  explicit AckLoginBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<AckLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AckLogin>(end);
    return o;
  }
};

inline flatbuffers::Offset<AckLogin> CreateAckLogin(
    flatbuffers::FlatBufferBuilder &_fbb,
    Protocol::C2S::eID id = Protocol::C2S::eID_AckLogin,
    flatbuffers::Offset<flatbuffers::Vector<float>> a = 0) {
  AckLoginBuilder builder_(_fbb);
  builder_.add_a(a);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<AckLogin> CreateAckLoginDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    Protocol::C2S::eID id = Protocol::C2S::eID_AckLogin,
    const std::vector<float> *a = nullptr) {
  auto a__ = a ? _fbb.CreateVector<float>(*a) : 0;
  return Protocol::C2S::CreateAckLogin(
      _fbb,
      id,
      a__);
}

}  // namespace C2S
}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_BODY_PROTOCOL_C2S_H_
