// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ID_PROTOCOL_C2S_H_
#define FLATBUFFERS_GENERATED_ID_PROTOCOL_C2S_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocol {
namespace C2S {

enum eID : uint32_t {
  eID_None = 20000,
  eID_AckLogin = 20001,
  eID_MIN = eID_None,
  eID_MAX = eID_AckLogin
};

inline const eID (&EnumValueseID())[2] {
  static const eID values[] = {
    eID_None,
    eID_AckLogin
  };
  return values;
}

inline const char * const *EnumNameseID() {
  static const char * const names[3] = {
    "None",
    "AckLogin",
    nullptr
  };
  return names;
}

inline const char *EnumNameeID(eID e) {
  if (flatbuffers::IsOutRange(e, eID_None, eID_AckLogin)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(eID_None);
  return EnumNameseID()[index];
}

}  // namespace C2S
}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_ID_PROTOCOL_C2S_H_
