// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOLIDRANGE_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOLIDRANGE_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocol {

enum GenerateRange : uint32_t {
  GenerateRange_L2L = 10000,
  GenerateRange_W2L = 11000,
  GenerateRange_L2W = 12000,
  GenerateRange_MIN = GenerateRange_L2L,
  GenerateRange_MAX = GenerateRange_L2W
};

inline const GenerateRange (&EnumValuesGenerateRange())[3] {
  static const GenerateRange values[] = {
    GenerateRange_L2L,
    GenerateRange_W2L,
    GenerateRange_L2W
  };
  return values;
}

inline const char *EnumNameGenerateRange(GenerateRange e) {
  switch (e) {
    case GenerateRange_L2L: return "L2L";
    case GenerateRange_W2L: return "W2L";
    case GenerateRange_L2W: return "L2W";
    default: return "";
  }
}

enum Range : uint32_t {
  Range_S2C = 10000,
  Range_C2S = 20000,
  Range_MIN = Range_S2C,
  Range_MAX = Range_C2S
};

inline const Range (&EnumValuesRange())[2] {
  static const Range values[] = {
    Range_S2C,
    Range_C2S
  };
  return values;
}

inline const char *EnumNameRange(Range e) {
  switch (e) {
    case Range_S2C: return "S2C";
    case Range_C2S: return "C2S";
    default: return "";
  }
}

}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_PROTOCOLIDRANGE_PROTOCOL_H_
