// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_COMMON_H_
#define FLATBUFFERS_GENERATED_COMMON_COMMON_H_

#include "flatbuffers/flatbuffers.h"

namespace Common {

struct Vector3;

struct V3;

struct Vector2;

struct Position;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) V3 FLATBUFFERS_FINAL_CLASS {
 private:
  float v_[3];

 public:
  V3()
      : v_() {
  }
  V3(flatbuffers::span<const float, 3> _v) {
    flatbuffers::CastToArray(v_).CopyFromSpan(_v);
  }
  const flatbuffers::Array<float, 3> *v() const {
    return &flatbuffers::CastToArray(v_);
  }
};
FLATBUFFERS_STRUCT_END(V3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vector2()
      : x_(0),
        y_(0) {
  }
  Vector2(float _x, float _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vector2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Position FLATBUFFERS_FINAL_CLASS {
 private:
  Common::Vector3 position_;
  float lookat_;

 public:
  Position()
      : position_(),
        lookat_(0) {
  }
  Position(const Common::Vector3 &_position, float _lookat)
      : position_(_position),
        lookat_(flatbuffers::EndianScalar(_lookat)) {
  }
  const Common::Vector3 &position() const {
    return position_;
  }
  float lookat() const {
    return flatbuffers::EndianScalar(lookat_);
  }
};
FLATBUFFERS_STRUCT_END(Position, 16);

}  // namespace Common

#endif  // FLATBUFFERS_GENERATED_COMMON_COMMON_H_
