// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_COMMON_H_
#define FLATBUFFERS_GENERATED_COMMON_COMMON_H_

#include "flatbuffers/flatbuffers.h"

namespace Common {

struct Vector3;

struct V3;

struct Vector2;

struct Position;

struct vecPosition;

struct Temp;
struct TempBuilder;

enum classType : int32_t {
  classType_None = 0,
  classType_Knight = 1,
  classType_Archer = 2,
  classType_Wizard = 3,
  classType_Max = 4,
  classType_MIN = classType_None,
  classType_MAX = classType_Max
};

inline const classType (&EnumValuesclassType())[5] {
  static const classType values[] = {
    classType_None,
    classType_Knight,
    classType_Archer,
    classType_Wizard,
    classType_Max
  };
  return values;
}

inline const char * const *EnumNamesclassType() {
  static const char * const names[6] = {
    "None",
    "Knight",
    "Archer",
    "Wizard",
    "Max",
    nullptr
  };
  return names;
}

inline const char *EnumNameclassType(classType e) {
  if (flatbuffers::IsOutRange(e, classType_None, classType_Max)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesclassType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) V3 FLATBUFFERS_FINAL_CLASS {
 private:
  float v_[3];

 public:
  V3()
      : v_() {
  }
  V3(flatbuffers::span<const float, 3> _v) {
    flatbuffers::CastToArray(v_).CopyFromSpan(_v);
  }
  const flatbuffers::Array<float, 3> *v() const {
    return &flatbuffers::CastToArray(v_);
  }
};
FLATBUFFERS_STRUCT_END(V3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vector2()
      : x_(0),
        y_(0) {
  }
  Vector2(float _x, float _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vector2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Position FLATBUFFERS_FINAL_CLASS {
 private:
  Common::Vector3 position_;
  float lookat_;

 public:
  Position()
      : position_(),
        lookat_(0) {
  }
  Position(const Common::Vector3 &_position, float _lookat)
      : position_(_position),
        lookat_(flatbuffers::EndianScalar(_lookat)) {
  }
  const Common::Vector3 &position() const {
    return position_;
  }
  float lookat() const {
    return flatbuffers::EndianScalar(lookat_);
  }
};
FLATBUFFERS_STRUCT_END(Position, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) vecPosition FLATBUFFERS_FINAL_CLASS {
 private:
  Common::Vector3 position_[3];
  float lookat_;

 public:
  vecPosition()
      : position_(),
        lookat_(0) {
  }
  vecPosition(float _lookat)
      : position_(),
        lookat_(flatbuffers::EndianScalar(_lookat)) {
  }
  vecPosition(flatbuffers::span<const Common::Vector3, 3> _position, float _lookat)
      : lookat_(flatbuffers::EndianScalar(_lookat)) {
    flatbuffers::CastToArray(position_).CopyFromSpan(_position);
  }
  const flatbuffers::Array<Common::Vector3, 3> *position() const {
    return &flatbuffers::CastToArray(position_);
  }
  float lookat() const {
    return flatbuffers::EndianScalar(lookat_);
  }
};
FLATBUFFERS_STRUCT_END(vecPosition, 40);

struct Temp FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TempBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X) &&
           VerifyField<float>(verifier, VT_Y) &&
           verifier.EndTable();
  }
};

struct TempBuilder {
  typedef Temp Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Temp::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Temp::VT_Y, y, 0.0f);
  }
  explicit TempBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Temp> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Temp>(end);
    return o;
  }
};

inline flatbuffers::Offset<Temp> CreateTemp(
    flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f) {
  TempBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

}  // namespace Common

#endif  // FLATBUFFERS_GENERATED_COMMON_COMMON_H_
