// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BODY_PROTOCOL_S2C_H_
#define FLATBUFFERS_GENERATED_BODY_PROTOCOL_S2C_H_

#include "flatbuffers/flatbuffers.h"

#include "id_generated.h"

namespace Protocol {
namespace S2C {

struct ReqLogin;
struct ReqLoginBuilder;

struct ReqLogin FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ReqLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_A = 6
  };
  Protocol::S2C::eID id() const {
    return static_cast<Protocol::S2C::eID>(GetField<uint32_t>(VT_ID, 10001));
  }
  int32_t a() const {
    return GetField<int32_t>(VT_A, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<int32_t>(verifier, VT_A) &&
           verifier.EndTable();
  }
};

struct ReqLoginBuilder {
  typedef ReqLogin Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(Protocol::S2C::eID id) {
    fbb_.AddElement<uint32_t>(ReqLogin::VT_ID, static_cast<uint32_t>(id), 10001);
  }
  void add_a(int32_t a) {
    fbb_.AddElement<int32_t>(ReqLogin::VT_A, a, 0);
  }
  explicit ReqLoginBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ReqLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ReqLogin>(end);
    return o;
  }
};

inline flatbuffers::Offset<ReqLogin> CreateReqLogin(
    flatbuffers::FlatBufferBuilder &_fbb,
    Protocol::S2C::eID id = Protocol::S2C::eID_ReqLogin,
    int32_t a = 0) {
  ReqLoginBuilder builder_(_fbb);
  builder_.add_a(a);
  builder_.add_id(id);
  return builder_.Finish();
}

}  // namespace S2C
}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_BODY_PROTOCOL_S2C_H_
