// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BODY_PROTOCOL_L2L_H_
#define FLATBUFFERS_GENERATED_BODY_PROTOCOL_L2L_H_

#include "flatbuffers/flatbuffers.h"

#include "id_generated.h"
#include "Common_generated.h"

namespace Protocol {
namespace L2L {

struct ReqLogin;
struct ReqLoginBuilder;

struct StartServer;
struct StartServerBuilder;

struct ReqLogin FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ReqLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_A = 6,
    VT_B = 8
  };
  Protocol::L2L::eID id() const {
    return static_cast<Protocol::L2L::eID>(GetField<uint32_t>(VT_ID, 10001));
  }
  int32_t a() const {
    return GetField<int32_t>(VT_A, 0);
  }
  const Common::Vector3 *b() const {
    return GetStruct<const Common::Vector3 *>(VT_B);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<int32_t>(verifier, VT_A) &&
           VerifyField<Common::Vector3>(verifier, VT_B) &&
           verifier.EndTable();
  }
};

struct ReqLoginBuilder {
  typedef ReqLogin Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(Protocol::L2L::eID id) {
    fbb_.AddElement<uint32_t>(ReqLogin::VT_ID, static_cast<uint32_t>(id), 10001);
  }
  void add_a(int32_t a) {
    fbb_.AddElement<int32_t>(ReqLogin::VT_A, a, 0);
  }
  void add_b(const Common::Vector3 *b) {
    fbb_.AddStruct(ReqLogin::VT_B, b);
  }
  explicit ReqLoginBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ReqLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ReqLogin>(end);
    return o;
  }
};

inline flatbuffers::Offset<ReqLogin> CreateReqLogin(
    flatbuffers::FlatBufferBuilder &_fbb,
    Protocol::L2L::eID id = Protocol::L2L::eID_ReqLogin,
    int32_t a = 0,
    const Common::Vector3 *b = 0) {
  ReqLoginBuilder builder_(_fbb);
  builder_.add_b(b);
  builder_.add_a(a);
  builder_.add_id(id);
  return builder_.Finish();
}

struct StartServer FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StartServerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_A = 6
  };
  Protocol::L2L::eID id() const {
    return static_cast<Protocol::L2L::eID>(GetField<uint32_t>(VT_ID, 10002));
  }
  int32_t a() const {
    return GetField<int32_t>(VT_A, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<int32_t>(verifier, VT_A) &&
           verifier.EndTable();
  }
};

struct StartServerBuilder {
  typedef StartServer Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(Protocol::L2L::eID id) {
    fbb_.AddElement<uint32_t>(StartServer::VT_ID, static_cast<uint32_t>(id), 10002);
  }
  void add_a(int32_t a) {
    fbb_.AddElement<int32_t>(StartServer::VT_A, a, 0);
  }
  explicit StartServerBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<StartServer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<StartServer>(end);
    return o;
  }
};

inline flatbuffers::Offset<StartServer> CreateStartServer(
    flatbuffers::FlatBufferBuilder &_fbb,
    Protocol::L2L::eID id = Protocol::L2L::eID_StartServer,
    int32_t a = 0) {
  StartServerBuilder builder_(_fbb);
  builder_.add_a(a);
  builder_.add_id(id);
  return builder_.Finish();
}

}  // namespace L2L
}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_BODY_PROTOCOL_L2L_H_
