// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ID_PROTOCOL_L2L_H_
#define FLATBUFFERS_GENERATED_ID_PROTOCOL_L2L_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocol {
namespace L2L {

enum eID : uint32_t {
  eID_None = 10000,
  eID_ReqLogin = 10001,
  eID_StartServer = 10002,
  eID_MIN = eID_None,
  eID_MAX = eID_StartServer
};

inline const eID (&EnumValueseID())[3] {
  static const eID values[] = {
    eID_None,
    eID_ReqLogin,
    eID_StartServer
  };
  return values;
}

inline const char * const *EnumNameseID() {
  static const char * const names[4] = {
    "None",
    "ReqLogin",
    "StartServer",
    nullptr
  };
  return names;
}

inline const char *EnumNameeID(eID e) {
  if (flatbuffers::IsOutRange(e, eID_None, eID_StartServer)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(eID_None);
  return EnumNameseID()[index];
}

}  // namespace L2L
}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_ID_PROTOCOL_L2L_H_
