// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ID_PROTOCOL_W2L_H_
#define FLATBUFFERS_GENERATED_ID_PROTOCOL_W2L_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocol {
namespace W2L {

enum eID : uint32_t {
  eID_None = 11000,
  eID_MIN = eID_None,
  eID_MAX = eID_None
};

inline const eID (&EnumValueseID())[1] {
  static const eID values[] = {
    eID_None
  };
  return values;
}

inline const char * const *EnumNameseID() {
  static const char * const names[2] = {
    "None",
    nullptr
  };
  return names;
}

inline const char *EnumNameeID(eID e) {
  if (flatbuffers::IsOutRange(e, eID_None, eID_None)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(eID_None);
  return EnumNameseID()[index];
}

}  // namespace W2L
}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_ID_PROTOCOL_W2L_H_
